// Client-side EBR draft export. Takes an account's real synthesis (already
// shown in the Playbooks tab) and renders it as a downloadable Word
// document — the "actual EBR draft" a CSM would walk into a meeting with,
// rather than just cards in the app.
//
// Deliberately simple: no template engine, no server round-trip, just the
// docx package building a document in the browser from data that's already
// on the page.

import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'
import type { Account, PriorityAction } from '../data/accounts'

function fmtMoney(n: number) {
  return n >= 1_000_000 ? `$${(n / 1_000_000).toFixed(1)}M` : `$${(n / 1_000).toFixed(0)}K`
}

function headerCell(text: string, width: number) {
  return new TableCell({
    width: { size: width, type: WidthType.DXA },
    shading: { type: ShadingType.CLEAR, fill: '1F2937', color: 'auto' },
    children: [new Paragraph({ children: [new TextRun({ text, bold: true, color: 'FFFFFF', size: 18 })] })],
    margins: { top: 60, bottom: 60, left: 100, right: 100 },
  })
}

function bodyCell(text: string, width: number) {
  return new TableCell({
    width: { size: width, type: WidthType.DXA },
    children: [new Paragraph({ children: [new TextRun({ text, size: 18 })] })],
    margins: { top: 60, bottom: 60, left: 100, right: 100 },
  })
}

function snapshotTable(account: Account) {
  const rows: [string, string][] = [
    ['ARR', fmtMoney(account.arr)],
    ['Renewal', `${account.renewalDaysOut} days out`],
    ['Health status', account.healthStatus],
    ['Open P1 bugs', String(account.openCriticalBugs)],
    ['Churn risk', `${account.churnRisk}/100`],
    ['Expansion score', `${account.expansionScore}/100`],
    ['NPS', String(account.npsScore)],
  ]
  const widths = [3000, 3000]
  return new Table({
    width: { size: 6000, type: WidthType.DXA },
    columnWidths: widths,
    rows: rows.map(
      ([label, value]) =>
        new TableRow({
          children: [
            new TableCell({
              width: { size: widths[0], type: WidthType.DXA },
              shading: { type: ShadingType.CLEAR, fill: 'F2F2F2', color: 'auto' },
              children: [new Paragraph({ children: [new TextRun({ text: label, bold: true, size: 18 })] })],
              margins: { top: 60, bottom: 60, left: 100, right: 100 },
            }),
            bodyCell(value, widths[1]),
          ],
        }),
    ),
  })
}

function priorityActionsTable(actions: PriorityAction[]) {
  const widths = [900, 3600, 1200, 1400, 2350]
  return new Table({
    width: { size: 9450, type: WidthType.DXA },
    columnWidths: widths,
    rows: [
      new TableRow({
        children: [
          headerCell('Role', widths[0]),
          headerCell('Action', widths[1]),
          headerCell('Urgency', widths[2]),
          headerCell('Deadline', widths[3]),
          headerCell('Rationale', widths[4]),
        ],
      }),
      ...actions.map(
        a =>
          new TableRow({
            children: [
              bodyCell(a.role, widths[0]),
              bodyCell(a.action, widths[1]),
              bodyCell(a.urgency, widths[2]),
              bodyCell(a.deadline, widths[3]),
              bodyCell(a.rationale, widths[4]),
            ],
          }),
      ),
    ],
  })
}

function playbookSection(title: string, steps: string[]) {
  return [
    new Paragraph({ text: title, heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 80 } }),
    ...steps.map(
      (s, i) =>
        new Paragraph({
          children: [new TextRun({ text: `${i + 1}. ${s}` })],
          spacing: { after: 100 },
        }),
    ),
  ]
}

export async function generateEbrDocx(account: Account): Promise<Blob> {
  const s = account.synthesis
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  const doc = new Document({
    sections: [
      {
        properties: { page: { size: { width: 12240, height: 15840 } } },
        children: [
          new Paragraph({
            children: [new TextRun({ text: account.name, bold: true, size: 40 })],
            spacing: { after: 40 },
          }),
          new Paragraph({
            children: [new TextRun({ text: 'Executive Business Review — Draft', italics: true, size: 24, color: '555555' })],
            spacing: { after: 40 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `Prepared ${today} · Generated by Delta, reviewed before sending`, size: 18, color: '777777' })],
            spacing: { after: 300 },
          }),

          new Paragraph({ text: 'Account Snapshot', heading: HeadingLevel.HEADING_1, spacing: { after: 120 } }),
          snapshotTable(account),

          new Paragraph({ text: 'The Pivot Point', heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 120 } }),
          new Paragraph({
            children: [new TextRun({ text: s.pivotPoint, size: 22 })],
            shading: { type: ShadingType.CLEAR, fill: 'EEF2FF', color: 'auto' },
            spacing: { after: 200 },
          }),

          new Paragraph({ text: 'Stakeholder Risk', heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 120 } }),
          new Paragraph({ children: [new TextRun({ text: s.stakeholderRiskHeatmap })], spacing: { after: 200 } }),

          new Paragraph({ text: 'Deployment Silo Analysis', heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 120 } }),
          new Paragraph({ children: [new TextRun({ text: s.deploymentSiloAnalysis })], spacing: { after: 200 } }),

          new Paragraph({ text: 'Priority Actions', heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 120 } }),
          priorityActionsTable(s.priorityActions),

          new Paragraph({ text: 'Multi-Threaded Playbook', heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 80 } }),
          ...playbookSection('CCO', s.playbook.cco),
          ...playbookSection('Enterprise CSM', s.playbook.csm),
          ...playbookSection('FDE Lead', s.playbook.fde),
        ],
      },
    ],
  })

  return Packer.toBlob(doc)
}

export function downloadEbrDocx(account: Account) {
  generateEbrDocx(account).then(blob => {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${account.name.replace(/\s+/g, '-')}-EBR-Draft.docx`
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
  })
}
